import {StyleSheet} from 'react-native';

export default StylesCss= StyleSheet.create({
     bcgrndC:{backgroundColor:'#FCFCFC',},
     bcPopUp:{backgroundColor:'#FCFCFC',},
     bcPopUp2:{backgroundColor:'#A9A9A9',
             // opacity: 0.5,
          },
     big:{color: '#000000',
          fontSize: 20,},
     Sname:{color: '#B39DDB',
          fontSize: 25},
     container1:{borderLeftWidth: 16,
               borderRightWidth: 16,
               borderTopWidth: 16,
               borderBottomWidth: 16,
               borderColor: '#FCFCFC'},
     container2:{borderLeftWidth: 16,
               borderRightWidth: 16,
               borderBottomWidth: 16,
               borderColor: '#FCFCFC'},
     container:{borderLeftWidth: 16,
               borderRightWidth: 16,
               borderTopWidth: 16,
               borderBottomWidth: 16,},
     containerbtn: {height :50,
               borderRadius:50,
               marginLeft: 50,
               marginRight : 50,
               marginTop: 50,
               marginBottom: 50,
          },
     Separator: {height: 1, 
               backgroundColor: '#b39ddb',  
               marginTop:10, 
               marginBottom: 10},
     StyleSold: {fontWeight: 'bold',
               fontSize: 70,
               fontFamily: 'Comic Sans MS',
               color: 'black'},
     Style$: {fontWeight: 'bold',
               fontSize: 40,},
     txtqui: {fontWeight:'bold',
               fontSize: 30,
               color:'black',
          marginLeft: 14,}

     
})