export default Dinfo = [
        { Title: "Type et Nom d'assurance",
          Date: "Date: 01 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 02 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 03 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 04 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 05 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 06 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 07 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 08 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 09 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 10 Fev 2019",},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 11 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 12 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 13 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 14 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 15 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 16 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 17 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 18 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 19 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 20 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 21 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 22 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 23 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 24 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 25 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 26 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 27 Fev 2019"},
        { Title: "Type et Nom d'assurance",
          Date: "Date: 05 Fev 2019"},
        
      ]
      