export default InfoHisto = [
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
      { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
      { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
      { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
      { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
      { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    { Title: "Assurance Nom",
      Date: "Today",
      Sold:"500"},
    
    
    
  ]
  